# Hello Jupyter Notebook

Jupyter notebooks is a great code editor for machine learning. Play around with the following cells to familiarize yourself with it.

### Cheat sheet

1. Double-click me!
2. Now you see me in edit mode (see the green box around me?) This means you can write stuff.
3. Now, hit Escape on your keyboard (see the box turn blue?) This means you are in command mode and can do lots of cool stuff. Try any of the following:
  - H (see **H**elp page)
  - A (insert cell **A**bove)
  - B (insert cell **B**elow)
4. Now, click me again, and execute me by running **Shift + Enter**. This is how you execute code in Jupyter. Try executing the following cells

In [1]:
print('Hello world!')

Hello world!

In [2]:
100/10*5

50

In [7]:
# When in doubt, you can use the '?' suffix to bring up the documentation
print?

Object `print` not found.

# Hello Python

### Variables

In [10]:
# this is how you define a variable
a = 10
print(a)
print(a+a)

some_variable = 'hello world'
print(some_variable)

10
20
hello world

In [8]:
# define variable my_name and assign your own name (e.g. 'david') to it. and then print it:

# YOUR CODE HERE:
my_name = "Nick"
print(my_name)

Nick

In [9]:
# Virtually everything in programming in case-sensitive
b = 10
B = 2000
print(b)

10

### Math operators

In [11]:
1 + 1

2

In [12]:
10/2

5

In [13]:
10*3

30

### Boolean operators

In [14]:
# Boolean (true/false) operators 
1 == 1

True

In [15]:
1 == 2

False

In [16]:
2 > 1

True

In [20]:
# joining boolean statements with 'and'
3 > 1 or 3 > 2000

True

In [18]:
print('hello' == 'hello')
print('hello' != 'bye')

True
True

### Arrays

In [21]:
# Arrays are denoted with square brackets - []
my_array = [100, 200, 300, 1000, 4200]
print(my_array)

[100, 200, 300, 1000, 4200]

In [25]:
# Accessing elements in an array (in programming, counting starts from 0!)
my_array[2]

300

In [23]:
# Accessing a range of elements in an array with colon ':'
my_array[0:4] # this gives us the zeroth to the fourth (non-inclusive) elements

[100, 200, 300, 1000]

In [24]:
my_array[:] # this gives us everything in an array

[100, 200, 300, 1000, 4200]

### Functions

In [28]:
# Defining a function
def add_2_numbers(a, b):
    return a + b

In [29]:
# Invoking a function
add_2_numbers(10, 200)

210

### Objects

In [30]:
# This is a class. Think of class as a blueprint for creating objects
class Person:
    def walk(self):
        print('i am walking!')
        
    def talk(self, topic):
        print('i am talking about ' + topic + '!')
        
    def add_2_numbers(self, a, b):
        return a + b

In [31]:
david = Person()

In [32]:
# This is known as a 'method'. A method is a function that belongs to an object
david.walk()

i am walking!

In [37]:
# Make david talk
# YOUR CODE HERE:
david.talk('stuff')

i am talking about stuff!

In [39]:
# Create another object and assign it to a variable of your choice. And then call all 3 of its methods:
# YOUR CODE HERE:
class Person2:
    def drink(self):
        print('I am drunk')

nick = Person2()
nick.drink()

I am drunk

# Hello pandas

In [40]:
import pandas as pd

In [ ]:
# pandas is an object (remember Person?) that can do things (i.e. it has methods).
# To see all the methods,  type the object (e.g. pd) followed by a dot (.) and hit "Tab". You can then scroll through its methods
pd.

In [43]:
# To load a csv file as a dataframe
# A dataframe is like your excel table
pd.read_csv('./data/bank-marketing-data/bank-additional-balanced-dataset.csv')

,Unnamed: 0,age,duration,campaign,pdays,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,...,month_sep,day_of_week_fri,day_of_week_mon,day_of_week_thu,day_of_week_tue,day_of_week_wed,poutcome_failure,poutcome_nonexistent,poutcome_success,y
0,0,56,261,1,999,0,1.1,93.994,-36.4,4.857,...,0,0,1,0,0,0,0,1,0,0
1,1,57,149,1,999,0,1.1,93.994,-36.4,4.857,...,0,0,1,0,0,0,0,1,0,0
2,2,37,226,1,999,0,1.1,93.994,-36.4,4.857,...,0,0,1,0,0,0,0,1,0,0
3,3,40,151,1,999,0,1.1,93.994,-36.4,4.857,...,0,0,1,0,0,0,0,1,0,0
4,4,56,307,1,999,0,1.1,93.994,-36.4,4.857,...,0,0,1,0,0,0,0,1,0,0
5,5,45,198,1,999,0,1.1,93.994,-36.4,4.857,...,0,0,1,0,0,0,0,1,0,0
6,6,59,139,1,999,0,1.1,93.994,-36.4,4.857,...,0,0,1,0,0,0,0,1,0,0
7,7,41,217,1,999,0,1.1,93.994,-36.4,4.857,...,0,0,1,0,0,0,0,1,0,0
8,8,24,380,1,999,0,1.1,93.994,-36.4,4.857,...,0,0,1,0,0,0,0,1,0,0
9,9,25,50,1,999,0,1.1,93.994,-36.4,4.857,...,0,0,1,0,0,0,0,1,0,0
10,10,41,55,1,999,0,1.1,93.994,-36.4,4.857,...,0,0,1,0,0,0,0,1,0,0
11,11,25,222,1,999,0,1.1,93.994,-36.4,4.857,...,0,0,1,0,0,0,0,1,0,0
12,12,29,137,1,999,0,1.1,93.994,-36.4,4.857,...,0,0,1,0,0,0,0,1,0,0
13,13,57,293,1,999,0,1.1,93.994,-36.4,4.857,...,0,0,1,0,0,0,0,1,0,0
14,14,35,146,1,999,0,1.1,93.994,-36.4,4.857,...,0,0,1,0,0,0,0,1,0,0
15,15,54,174,1,999,0,1.1,93.994,-36.4,4.857,...,0,0,1,0,0,0,0,1,0,0
16,16,35,312,1,999,0,1.1,93.994,-36.4,4.857,...,0,0,1,0,0,0,0,1,0,0
17,17,46,440,1,999,0,1.1,93.994,-36.4,4.857,...,0,0,1,0,0,0,0,1,0,0
18,18,50,353,1,999,0,1.1,93.994,-36.4,4.857,...,0,0,1,0,0,0,0,1,0,0
19,19,39,195,1,999,0,1.1,93.994,-36.4,4.857,...,0,0,1,0,0,0,0,1,0,0
20,20,30,38,1,999,0,1.1,93.994,-36.4,4.857,...,0,0,1,0,0,0,0,1,0,0
21,21,55,262,1,999,0,1.1,93.994,-36.4,4.857,...,0,0,1,0,0,0,0,1,0,0
22,22,55,342,1,999,0,1.1,93.994,-36.4,4.857,...,0,0,1,0,0,0,0,1,0,0
23,23,41,181,1,999,0,1.1,93.994,-36.4,4.857,...,0,0,1,0,0,0,0,1,0,0
24,24,37,172,1,999,0,1.1,93.994,-36.4,4.857,...,0,0,1,0,0,0,0,1,0,0
25,25,35,99,1,999,0,1.1,93.994,-36.4,4.857,...,0,0,1,0,0,0,0,1,0,0
26,26,59,93,1,999,0,1.1,93.994,-36.4,4.857,...,0,0,1,0,0,0,0,1,0,0
27,27,39,233,1,999,0,1.1,93.994,-36.4,4.857,...,0,0,1,0,0,0,0,1,0,0
28,28,54,255,2,999,0,1.1,93.994,-36.4,4.857,...,0,0,1,0,0,0,0,1,0,0
29,29,55,362,1,999,0,1.1,93.994,-36.4,4.857,...,0,0,1,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9610,41128,31,456,2,999,0,-1.1,94.767,-50.8,1.044,...,0,0,0,0,0,1,0,1,0,1
9611,41130,31,260,1,999,0,-1.1,94.767,-50.8,1.041,...,0,0,0,1,0,0,0,1,0,1
9612,41132,41,597,2,3,2,-1.1,94.767,-50.8,1.041,...,0,0,0,1,0,0,0,0,1,1
9613,41134,25,244,1,999,0,-1.1,94.767,-50.8,1.041,...,0,0,0,1,0,0,0,1,0,1
9614,41138,58,344,2,999,0,-1.1,94.767,-50.8,1.041,...,0,0,0,1,0,0,0,1,0,1
9615,41140,33,237,2,999,0,-1.1,94.767,-50.8,1.040,...,0,1,0,0,0,0,0,1,0,1
9616,41141,37,315,1,999,0,-1.1,94.767,-50.8,1.040,...,0,1,0,0,0,0,0,1,0,1
9617,41142,43,741,4,999,2,-1.1,94.767,-50.8,1.040,...,0,1,0,0,0,0,1,0,0,1
9618,41145,26,528,3,999,0,-1.1,94.767,-50.8,1.040,...,0,1,0,0,0,0,0,1,0,1
9619,41146,41,252,4,999,0,-1.1,94.767,-50.8,1.040,...,0,1,0,0,0,0,0,1,0,1
9620,41147,25,712,2,19,1,-1.1,94.767,-50.8,1.040,...,0,1,0,0,0,0,0,0,1,1
9621,41148,35,397,3,999,0,-1.1,94.767,-50.8,1.040,...,0,1,0,0,0,0,0,1,0,1
9622,41151,41,526,2,6,1,-1.1,94.767,-50.8,1.039,...,0,0,1,0,0,0,0,0,1,1
9623,41153,67,655,2,5,5,-1.1,94.767,-50.8,1.039,...,0,0,1,0,0,0,0,0,1,1
9624,41156,41,545,2,999,0,-1.1,94.767,-50.8,1.039,...,0,0,1,0,0,0,0,1,0,1
9625,41158,35,363,1,999,0,-1.1,94.767,-50.8,1.035,...,0,0,0,0,1,0,0,1,0,1
9626,41159,35,514,1,9,4,-1.1,94.767,-50.8,1.035,...,0,0,0,0,1,0,0,0,1,1
9627,41160,33,843,1,999,0,-1.1,94.767,-50.8,1.035,...,0,0,0,0,1,0,0,1,0,1
9628,41163,35,385,3,4,2,-1.1,94.767,-50.8,1.035,...,0,0,0,0,1,0,0,0,1,1
9629,41164,54,1868,2,10,1,-1.1,94.767,-50.8,1.035,...,0,0,0,0,1,0,0,0,1,1
9630,41165,38,403,2,999,0,-1.1,94.767,-50.8,1.030,...,0,0,0,0,0,1,0,1,0,1
9631,41166,32,651,1,999,1,-1.1,94.767,-50.8,1.030,...,0,0,0,0,0,1,1,0,0,1
9632,41171,33,112,1,999,0,-1.1,94.767,-50.8,1.031,...,0,0,0,1,0,0,0,1,0,1
9633,41172,31,353,1,999,0,-1.1,94.767,-50.8,1.031,...,0,0,0,1,0,0,0,1,0,1
9634,41173,62,329,1,999,2,-1.1,94.767,-50.8,1.031,...,0,0,0,1,0,0,1,0,0,1
9635,41174,62,208,1,1,6,-1.1,94.767,-50.8,1.031,...,0,0,0,1,0,0,0,0,1,1
9636,41178,62,483,2,6,3,-1.1,94.767,-50.8,1.031,...,0,0,0,1,0,0,0,0,1,1
9637,41181,37,281,1,999,0,-1.1,94.767,-50.8,1.028,...,0,1,0,0,0,0,0,1,0,1
9638,41183,73,334,1,999,0,-1.1,94.767,-50.8,1.028,...,0,1,0,0,0,0,0,1,0,1
9639,41186,44,442,1,999,0,-1.1,94.767,-50.8,1.028,...,0,1,0,0,0,0,0,1,0,1

In [44]:
# Assign the output of this method to a variable
df = pd.read_csv('./data/bank-marketing-data/bank-additional-balanced-dataset.csv')

In [46]:
# Again, df is an object that can do things (i.e. it has methods). Add a dot after df and hit "Tab to see its methods"
df.

AttributeError: 'DataFrame' object has no attribute 'Tab'

In [48]:
# When in doubt about a method, you can either go to the official documentation (just google the library and method name), or use our good friend (?) 

# For example:
df.to_csv?

In [50]:
# Pick another random method of df and find out what it does by using '?' 

# YOUR CODE HERE:
df.columns

Index([u'Unnamed: 0', u'age', u'duration', u'campaign', u'pdays', u'previous',
       u'emp.var.rate', u'cons.price.idx', u'cons.conf.idx', u'euribor3m',
       u'nr.employed', u'job_admin.', u'job_blue-collar', u'job_entrepreneur',
       u'job_housemaid', u'job_management', u'job_retired',
       u'job_self-employed', u'job_services', u'job_student',
       u'job_technician', u'job_unemployed', u'job_unknown',
       u'marital_divorced', u'marital_married', u'marital_single',
       u'marital_unknown', u'education_basic.4y', u'education_basic.6y',
       u'education_basic.9y', u'education_high.school',
       u'education_illiterate', u'education_professional.course',
       u'education_university.degree', u'education_unknown', u'default_no',
       u'default_unknown', u'default_yes', u'housing_no', u'housing_unknown',
       u'housing_yes', u'loan_no', u'loan_unknown', u'loan_yes',
       u'contact_cellular', u'contact_telephone', u'month_apr', u'month_aug',
       u'month_dec', u'month_jul', u'month_jun', u'month_mar', u'month_may',
       u'month_nov', u'month_oct', u'month_sep', u'day_of_week_fri',
       u'day_of_week_mon', u'day_of_week_thu', u'day_of_week_tue',
       u'day_of_week_wed', u'poutcome_failure', u'poutcome_nonexistent',
       u'poutcome_success', u'y'],
      dtype='object')

In [ ]:
# Some useful pandas methods:
# df.head(), df.head(7)
# df.describe()
# df.columns #Note: this is not a method, but an attribute. Notice that there are no brackets ()

In [57]:
# pd.Series
# A series is like a column in table.
# You can access series by referring to its column name:
# Example:
df['y'].value_counts()

# Try accessing other columns! (Use df.columns to see what columns are available to you)

0    5000
1    4640
Name: y, dtype: int64

In [ ]:
# we can see unique values in a series by using the .value_counts() method
df['y'].value_counts()

# Hello Shell

To run shell commands in jupyter notebook, simply prefix the command with an exclamation mark (!)

In [1]:
# to list the contents of a directory
!ls

1-hello-jupyter.ipynb
2-classification-model-workshop-starter-code.ipynb
3-classification-model-workshop-solutions.ipynb
bin
classification-model-workshop-solutions.ipynb
comparing-models.ipynb
data
data-preprocessing.ipynb
full-analysis.ipynb
hello-jupyter.ipynb
logistic-regression-formula-playground.ipynb
README.md
requirements.txt

In [2]:
# to print working (i.e. current) directory
!pwd

/home/ubuntu/code/sim-workshop/workshop-repo-7

In [ ]:
# to change directory
# cd <name-of-directory>

! cd .. && pwd

In [ ]:
# To join shell commands, use &&
! cd ../.. && pwd
! cd data/bank-marketing-data && ls -l # -l are options of the ls command

In [3]:
# Hello git

In [ ]:
# 1. Create git repository in a folder
!git init

In [ ]:
# 2. Connect your local repository (i.e. on your desktop) to the remote repository (e.g. on github.com)
!git remote add origin YOUR_GITHUB_REPO_URL

In [ ]:
# 3. See the status of your git commits (this command can be run at anytime)
!git status

In [ ]:
# 3. Add your files to staging
!git add . # . means everything in the current working directory
# you can also add files or directories individually (e.g. git add my-file; git add my-directory/my-file; git add my-directory)

In [ ]:
# 4. Commit your files to the repo
!git commit -m "your awesome commit message"

In [ ]:
# !git push -u origin master
!git push https://<your_username>:<your_password>@https://YOUR_GITHUB_REPO_URL --all